from __future__ import annotations

from pathlib import Path
from typing import Sequence

import numpy as np

from ..structures import Atoms


def write_poscar(filename: str | Path, atoms: Atoms, *, direct: bool = True) -> None:
    """
    Write a POSCAR file.

    Parameters
    ----------
    filename : str or pathlib.Path
        Path of the output POSCAR file.
    atoms : isse.structures.Atoms
        Atomic configuration to write. The cell is interpreted in angstrom and
        positions are interpreted in angstrom.
    direct : bool, optional
        If ``True``, write fractional Direct coordinates. If ``False``, write
        Cartesian coordinates. The default is ``True``.

    Returns
    -------
    None
        The function writes the file and returns ``None``.

    Notes
    -----
    POSCAR positions are grouped by chemical species in agreement with the
    species/count header lines. The input ``atoms`` object is not modified.
    """
    species, counts = _species_counts_in_order(atoms.symbols)
    positions = _scaled_positions(atoms) if direct else atoms.positions
    coord_label = "Direct" if direct else "Cartesian"
    header = atoms.info.get("header", "Generated by ISSE")

    order = [
        index
        for symbol in species
        for index, atom_symbol in enumerate(atoms.symbols)
        if atom_symbol == symbol
    ]

    with Path(filename).open("w") as file:
        file.write(f"{header}\n")
        file.write("1.0\n")
        for row in atoms.cell:
            file.write(_format_vector(row) + "\n")
        file.write(" ".join(species) + "\n")
        file.write(" ".join(str(count) for count in counts) + "\n")
        file.write(f"{coord_label}\n")
        for index in order:
            file.write(_format_vector(positions[index]) + "\n")


def _format_vector(vector: Sequence[float]) -> str:
    return " ".join(f"{float(value):.16g}" for value in vector)


def _scaled_positions(atoms: Atoms) -> np.ndarray:
    return np.linalg.solve(atoms.cell.T, atoms.positions.T).T


def _species_counts_in_order(symbols: Sequence[str]) -> tuple[list[str], list[int]]:
    species: list[str] = []
    counts: list[int] = []
    for symbol in symbols:
        if symbol not in species:
            species.append(symbol)
            counts.append(symbols.count(symbol))
    return species, counts
